### PR TITLE
Fixes for libexpat, libgme, and opencl_icd

### PR DESCRIPTION
**Pull request by epilsits**

### CODE REVIEW

**Comment by DeadSix27** [comment]
Thanks :)

Closes #29

**Review by hydra3333 — COMMENTED** [review]
Just wondering, for libexpat I use this in an old copy of rdp's script and it seems to build.  Am I doing something wrong nowadays or is that still valid ?

      if [[ ! -f ./configure ]]; then
        autoreconf -fiv
      fi
      generic_configure_make_install

**Review by hydra3333 — COMMENTED** [review]
Just wondering.  This line in the OpenCL icd build section,

> 'sed -i.bak \'s/Devpkey.h/devpkey.h/\' icd_windows_hkr.c',

seems to change an include to expect a file named devpkey.h which isn't in the repository https://github.com/KhronosGroup/OpenCL-ICD-Loader afaik.
When you cross-compile, how is that file sourced (i.e. what do you do to retrieve it and put it in the right place beforehand) ?

**Comment by DeadSix27** [comment]
@hydra3333 devpkey is part of mingw, and about the expat that is a line that generates ./configure if it doesnt exist, so if it still doesnt exist (in the source, before doing anything) keep that line.

**Comment by hydra3333** [comment]
@DeadSix27 ah, light bulb finally flickers on, it took a while, thank you.  I was under a false impression that devpkey came with an installed windows developer package of some kind.  I'll go back and re-read the various comments referencing mingw.  And have a look at your different expat patch/build-method.

Nice work !

**Pull request merged**
