### PR TITLE
just a few thoughts/suggestions

### PR DESCRIPTION
**Pull request by hydra3333**
I'm guessing you won't like them; anyway, they're there in case something may be useful.

### CODE REVIEW

**Comment by DeadSix27** [comment]
Editing the default config is unnecessary, since users can customize that, leave that as is. If you think ffmpeg_shared should be a default build, just leave it in your config, problem solved. 
<script_name> looks not so nice imo, ill leave that as is as well.
Adding log to the run_process is unnecessary too, as debug will show those lines (enable debug in config...)

I'll go through all the package changes later.

What you can do if it matters to you, open a PR with purely grammar fixes, I do not see it as a high priority so I only ever fix them if I come across obvious misspells

**Comment by DeadSix27** [comment]
About " ... but LSW (used in X264.exe) depends on it ..."
I won't add it back, it's gone for good (ffmpeg will remove it at some point). If LSW needs it they have to update or use alternatives.

**Comment by hydra3333** [comment]
Cool.

**Comment by DeadSix27** [comment]
@hydra3333 Ok, done, added most of the stuff from your PR, couldn't cherry pick because you made it in 1 big commit rather than splitting it into many small ones (which I try to do from now on, as you saw now)

**Comment by hydra3333** [comment]
Ok !  Thank you for your ongoing great work !

Sorry about the big commit ... I did know better from circa 40 years ago, but forgot to actually be organised 👍

**Pull request closed without merging**
