### PR TITLE
packages/vulkan: fix building

### PR DESCRIPTION
**Pull request by ghost**
Adds dxgi dependency introduced in https://github.com/KhronosGroup/Vulkan-Loader/commit/2e14b61788de447ba56c04a4f41ec9b347304a5d

### CODE REVIEW

**Comment by DeadSix27** [comment]
Thanks! I'll test it when I find the time, but if it's just linking to lib dxgi that's required, the change LGMT.

**Comment by LigH-de** [comment]
Has been tested in [a MABS issue](https://github.com/m-ab-s/media-autobuild_suite/issues/1380#issuecomment-531168376)

**Comment by DeadSix27** [comment]
Alright, thanks for the patch. Took a while due to hospital time in-between.

**Comment by hydra3333** [comment]
eek, take care old bean.

**Pull request merged**
