### PR TITLE
miscellaneous updates

### PR DESCRIPTION
**Pull request by hydra3333**
mediainfo builds from git (removes a runtime error on win10)
vpx builds vpxenc.exe and vpxdec.exe
preliminary support for .7z source files which do not contain a top level folder in the .7z
new dependency on package p7zip-full to unzip .7z files (eg in ubuntu sudo apt-get install -y p7zip-full)

### CODE REVIEW

**Comment by hydra3333** [comment]
Damn, I must have done something wrong.

```
ERROR: vapoursynth-script >= 42 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
[01:36:43][ERROR] Error [1] running process: './configure --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-cross-compile --enable-pic --enable-libsoxr --enable-libass --enable-iconv --enable-libtwolame --enable-libzvbi --enable-libcaca --enable-libmodplug --enable-cuvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libgsm --enable-libopus --enable-bzlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-dxva2 --enable-avisynth --enable-vapoursynth --enable-gray --enable-libmysofa --enable-libflite --enable-lzma --enable-libsnappy --enable-libzimg --enable-libx264 --enable-libx265 --enable-libaom --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libxavs --enable-libxvid --enable-libgme --enable-runtime-cpudetect --enable-libfribidi --enable-gnutls --enable-gmp --enable-fontconfig --enable-libfontconfig --enable-libfreetype --enable-opengl --enable-d3d11va --enable-libmfx --disable-schannel --disable-gcrypt --enable-gpl --extra-version=DeadSix27/python_cross_compile_script --pkg-config-flags="--static" --extra-cflags="-DLIBTWOLAME_STATIC" --extra-cflags="-DMODPLUG_STATIC"  --enable-libbluray --prefix=/home/u/Desktop/ds27/workdir/x86_64_products/ffmpeg_static_non_free_opencl.installed --disable-shared --enable-static --enable-opencl --enable-nonfree --enable-libfdk-aac --enable-decklink' in '/home/u/Desktop/ds27/workdir/x86_64_products/ffmpeg_static_non_free_opencl'
[01:36:43][ERROR] You can try deleting the product/dependency folder: '/home/u/Desktop/ds27/workdir/x86_64_products/ffmpeg_static_non_free_opencl' and re-run the script
+ exit 1
```

I'll try again without vapoursynth.

**Comment by hydra3333** [comment]
didn't work with new opencl

**Comment by DeadSix27** [comment]
@hydra3333 I disabled vpxenc/dec because its just the library, we need to make a product for those, but I never really use em so I didn't add it yet.

**Comment by hydra3333** [comment]
ok

**Pull request closed without merging**
