### PR TITLE
build the latest mediainfo from GIT

### PR DESCRIPTION
**Pull request by hydra3333**
should do away with "file not found" under windows, fixed in a version greater than 0.74

### CODE REVIEW

**Comment by DeadSix27** [comment]
@hydra3333 No need to comment it out, just remove those lines :)
Also, no need to add the depends to mediainfo, if you check libmediainfo, it depends on those things already, so they'll always be build.

**Comment by hydra3333** [comment]
> Also, no need to add the depends to mediainfo, if you check libmediainfo, it depends on those things already, so they'll always be build.

yes.  I was being "safe" about it.

> No need to comment it out, just remove those lines :)

OK, I just need to figure out how to revoke a pull :)

**Comment by DeadSix27** [comment]
@hydra3333 
image
^Button bottom right.
But you can just commit again to this PR and only remove the branch line

**Review by hydra3333 — COMMENTED** [review]
ah ok, looking now ...

**Pull request closed without merging**
