### PR TITLE
general code cleanup and improvements

### PR DESCRIPTION
**Pull request by DeadSix27**

### CODE REVIEW

**Review by hydra3333 — COMMENTED** [review]
Just checking, is
, 'svt_av1', 'svt_av1', 'svt_vp9'
supposed to be
, 'svt_av1', 'svt_vp9', 'svt-hevc' 
in 'ffmpeg_static_non_free_opencl' ?

**Review by hydra3333 — COMMENTED** [review]
the patch https://github.com/OpenVisualCloud/SVT-VP9/pull/59.patch already appears to be applied ?

**Comment by DeadSix27** [comment]
Ye, they merged  that PR now. 

Also the ffmpeg_static_non_free_opencl was a bug,
it's in: https://github.com/DeadSix27/python_cross_compile_script/blob/master/packages/products/ffmpeg_svtav1_test.py

And only av1 seems to build. .and even that crashes for me.. so i didn't add svt to anything

**Comment by hydra3333** [comment]
OK.  Good oh. 
I thought they were also added to one of the ffmpeg_depends ? Maybe not.

**Comment by DeadSix27** [comment]
Nope. Only ffmpeg_svtav1_test.. and that only has av1

**Comment by hydra3333** [comment]
Thanks, and good luck :)

**Pull request merged**
